diffractive_vmp:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py diffractive_vmp

diffractive_vmp:generate:
  stage: generate
  extends: .phy_benchmark
  needs: ["common:detector", "diffractive_vmp:compile"]
  parallel:
    matrix:
      - VM: jpsi
  timeout: 1 hours
  script:
    # FIXME eAu beams
    - bash benchmarks/diffractive_vmp/get.sh --config diffractive_${vm} --ebeam 18 --pbeam 110

diffractive_vmp:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["diffractive_vmp:generate"]
  parallel:
    matrix:
      - VM: jpsi
  timeout: 96 hour
  script:
    # FIXME eAu beams
    - bash benchmarks/diffractive_vmp/diffractive_vmp.sh --config diffractive_${vm} --ebeam 18 --pbeam 110
  retry:
    max: 2
    when:
      - runner_system_failure

diffractive_vmp:results:
  stage: collect
  needs: ["diffractive_vmp:simulate"]
  script:
    - collect_tests.py diffractive_vmp
