image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

default:
  tags:
    - silicon
  artifacts:
    expire_in: 3 days
    paths:
      - detector/
      - results/

stages:
  - init
  - config
  - generate
  - process
  - analyze
  - collect
  - cleanup
  - finish

detector:
  stage: init
  script:
    - mkdir -p detector
    - bash init/build_detector.sh

include:
  - local: 'dis/config.yml'
  - local: 'dummy/config.yml'
  - local: 'dvmp/config.yml'

summary:
  stage: finish
  needs: ["dis:results", "dummy:results", "dvmp:results"]
  script:
    - echo "All benchmarks passed"
