image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest

default:
  tags:
    - silicon
  artifacts:
    expire_in: 3 days

stages:
  - generate
  - process
  - analyze
  - collect
  - finish

include:
  - local: 'dis/config.yml'
  - local: 'dvmp/config.yml'

summary:
  stage: finish
  needs: ["dis:results", "dvmp:results"]
  script:
    - echo "All benchmarks passed"
