image: ${BENCHMARKS_REGISTRY}/${BENCHMARKS_CONTAINER}${BENCHMARKS_SIGIL}${BENCHMARKS_TAG}

variables:
  RECO: "eicrecon"
  DETECTOR: epic
  DETECTOR_CONFIG: epic_craterlake
  SNAKEMAKE_FLAGS: '--cache'

workflow:
  name: '$PIPELINE_NAME'

default:
  id_tokens:
    CI_JOB_JWT:
      aud: ${CI_SERVER_PROTOCOL}://${CI_SERVER_HOST}
  before_script:
    - source .local/bin/env.sh
  tags:
    - phy-scratch
  artifacts:
    expire_in: 3 days
    paths:
      - .local/detector
      - .local/lib
      - .local/bin
      - .local/include
      - .local/share
      - .local/root_build
      - .snakemake/log
      - results
      - config
      - .env
      - summary.txt
    reports:
      dotenv: .env
    when: always

stages:
  - status-pending
  - config
  - compile
  - generate
  - simulate
  - collect
  - finish
  - status-report

.status:
  image: curlimages/curl:latest
  rules:
    - if: $GITHUB_SHA !~ /^$/ # when GITHUB_SHA non-empty
  before_script: []
  script:
    - |
      curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${GITHUB_REPO_STATUS_TOKEN}" \
        "https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA}" \
        -d '{"state":"'"${STATE}"'",
             "target_url":"'"${CI_PIPELINE_URL}"'",
             "description":"'"$(TZ=America/New_York date)"'",
             "context":"eicweb/physics_benchmarks ('"${BENCHMARKS_TAG}"', '"$DETECTOR_CONFIG"')"
            }' ;
  retry:
    max: 2
    when:
      - runner_system_failure

benchmarks:physics:pending:
  stage: status-pending
  extends: .status
  variables:
    STATE: "pending"
  when: always

common:setup:
  stage: config
  before_script:
    - |
      if [[ -z "${COMMON_BENCH_VERSION}" ]] ; then
        export COMMON_BENCH_VERSION="master" 
      fi
      echo "COMMON_BENCH_VERSION = ${COMMON_BENCH_VERSION}" 
      echo "COMMON_BENCH_VERSION=${COMMON_BENCH_VERSION}" >> .env
  script:
    - git clone -b "${COMMON_BENCH_VERSION}" https://eicweb.phy.anl.gov/EIC/benchmarks/common_bench.git setup 
    - source setup/bin/env.sh && ./setup/bin/install_common.sh
    - mkdir_local_data_link sim_output
    - mkdir_local_data_link datasets
    - mkdir -p results
    - mkdir -p config
    - print_env.sh

.compile_benchmark:
  needs:
    - ["common:setup"]
  before_script:
    - source .local/bin/env.sh  
  retry:
    max: 2
    when:
      - runner_system_failure

.phy_benchmark:
  needs:
    - ["common:setup"]
  before_script:
    - source .local/bin/env.sh
    - source /opt/detector/epic-main/bin/thisepic.sh
    - ls -lrtha 
    - ln -s "${LOCAL_DATA_PATH}/sim_output" sim_output
    - ln -s "${LOCAL_DATA_PATH}/datasets/data" data
    - mkdir -p "$SNAKEMAKE_OUTPUT_CACHE"
    - ls -lrtha
  retry:
    max: 2
    when:
      - runner_system_failure

include:
  - local: 'benchmarks/Exclusive-Diffraction-Tagging/diffractive_vm/config.yml'
  - local: 'benchmarks/Exclusive-Diffraction-Tagging/demp/config.yml'
  - local: 'benchmarks/Exclusive-Diffraction-Tagging/semi_coherent/config.yml'
    #- local: 'benchmarks/Exclusive-Diffraction-Tagging/dvmp/config.yml'
  - local: 'benchmarks/Exclusive-Diffraction-Tagging/dvcs/config.yml'
  - local: 'benchmarks/Exclusive-Diffraction-Tagging/tcs/config.yml'
  - local: 'benchmarks/Exclusive-Diffraction-Tagging/u_omega/config.yml'
  - local: 'benchmarks/Inclusive/dis/config.yml'

summary:
  stage: finish
  needs:
    - "diffractive_vm:results"
    - "demp:results"
    - "dis:results"
    - "dvcs:results"
    - "tcs:results"
    - "u_omega:results"
  script:
    - collect_benchmarks.py
    - find results -print | sort | tee summary.txt
  artifacts:
    paths:
      - summary.txt
      - results/*
#    reports:
#      junit: ["results/dvcs/report2.xml"]
  retry:
    max: 2
    when:
      - runner_system_failure

benchmarks:physics:success:
  stage: status-report
  dependencies: []
  extends: .status
  variables:
    STATE: "success"
  after_script:
    # Cleanup scratch space
    - rm -rfv $LOCAL_DATA_PATH
  when: on_success

benchmarks:physics:failure:
  stage: status-report
  dependencies: []
  extends: .status
  variables:
    STATE: "failure"
  when: on_failure
