demp:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 demp_compile

demp:generate:
  stage: generate
  extends: .phy_benchmark
  needs: ["common:detector", "demp:compile"]
  timeout: 1 hours
  script:
    - snakemake --cores 1 input/demp/eic_DEMPGen_5on41_ip6_pi+_1B_{1,2,3,4,5}.hepmc

demp:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["demp:generate"]
  timeout: 2 hours
  script:
    - snakemake --cores 5 demp_run_locally
  retry:
    max: 2
    when:
      - runner_system_failure

demp:results:
  stage: collect
  needs: ["demp:simulate"]
  script:
    - collect_tests.py demp
