demp:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py demp

demp:simulate:
  stage: simulate
  extends: .phy_benchmark
  tags:
    - phy
  needs: ["common:detector", "demp:compile"]
  script:
    #- bash benchmarks/demp/demp.sh --all
    - bash benchmarks/demp/demp.sh --data-init --sim --rec

demp:results:
  stage: collect
  needs: ["demp:simulate"]
  script:
    - ls -lrth
      #pip install junitparser
      #- python demp/scripts/merge_results.py
