dvmp:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 dvmp_compile

dvmp:generate:
  needs: ["dvmp:compile"]
  image: eicweb.phy.anl.gov:4567/monte_carlo/lager/lager:unstable
  extends: .phy_benchmark
  stage: generate
  timeout: 1 hours
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 5 input/gen-jpsi_barrel_muon_${JUGGLER_N_EVENTS}.hepmc input/gen-jpsi_barrel_electron_${JUGGLER_N_EVENTS}.hepmc

dvmp:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["dvmp:generate"]
  timeout: 2 hour
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 5 dvmp_run_locally
  retry:
    max: 2
    when:
      - runner_system_failure
