demp:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 demp_compile

demp:simulate:
  stage: simulate
  extends: .phy_benchmark
  timeout: 2 hours
  script:
    - snakemake --cache --cores 5 demp_run_locally
  retry:
    max: 2
    when:
      - runner_system_failure

demp:results:
  stage: collect
  needs: ["demp:simulate"]
  script:
    - collect_tests.py demp
