dglazier_benchmark:compile:
  extends: .phy_benchmark 
  stage: compile
  script:
    - echo "You can compile your code here!"

dglazier_benchmark:simulate:
  extends: .phy_benchmark
  stage: simulate
  needs: ["common:setup"]
  timeout: 10 hour
  script:
    - echo "I will simulate detector response here!"
    - config_file=benchmarks/dglazier_benchmark/setup.config
    - source $config_file
    - if [ "$USE_SIMULATION_CAMPAIGN" = true ] ; then
    -     echo "Using simulation campaign so skipping this step!"
    - else
    -     echo "Grabbing raw events from S3 and running Geant4"
    -     bash benchmarks/dglazier_benchmark/simulate.sh
    -     echo "Geant4 simulations done! Starting eicrecon now!"
    -     bash benchmarks/dglazier_benchmark/reconstruct.sh
    - fi
    - echo "Finished simulating detector response"
  retry:
    max: 2
    when:
      - runner_system_failure

    
dglazier_benchmark:results:
  extends: .phy_benchmark
  stage: collect
  needs:
    - ["dglazier_benchmark:simulate"]
  script:
    - echo "I will collect results here!"
    - mkdir -p results/dglazier_benchmark
    - mkdir -p benchmark_output
    - config_file=benchmarks/dglazier_benchmark/setup.config
    - source $config_file
    - if [ "$USE_SIMULATION_CAMPAIGN" = true ] ; then
    -     echo "Using simulation campaign!"
    -     snakemake --cores 2 ../../sim_output/campaign_24.07.0_combined_45files.eicrecon.tree.edm4eic.plots_figures/benchmark_rho_mass.pdf
    -     cp ../../sim_output/campaign_24.07.0_combined_45files.eicrecon.tree.edm4eic.plots_figures/*.pdf results/dglazier_benchmark/
    - else
    -     echo "Not using simulation campaign!"
    -     bash benchmarks/dglazier_benchmark/analyze.sh
    -     cp sim_output/nocampaign/plots_figures/*.pdf results/dglazier_benchmark/
    - fi
    - echo "Finished, copying over json now"
    - cp benchmark_output/u_rho_eff.json results/dglazier_benchmark/
    - echo "Finished copying!"
    - collect_tests.py your_benchmark
    - echo "Finished collecting!"
 