dis:generate:
  stage: initialize
  image: eicweb.phy.anl.gov:4567/eic/juggler/juggler:latest
  needs: []
  timeout: 1 hours
  artifacts:
    paths:
      - results
  script:
    - bash dis/gen.sh

dis:process:
  stage: process
  needs: ["detector", "dis:generate"]
  timeout: 1 hour
  artifacts:
    paths:
      - results
  script:
    - echo "DIS benchmarks"

dis:results:
  stage: collect
  needs: ["dis:process"]
  script:
    - echo "All DIS benchmarks successful"
