dvmp:generate:
  image: eicweb.phy.anl.gov:4567/monte_carlo/lager/lager:unstable
  stage: initialize
  needs: []
  timeout: 1 hours
  cache:
    key:
      files:
        - benchmarks/dvmp/generator/jpsi_central.json
        - benchmarks/dvmp/scripts/jpsi_central-generate.sh
      prefix: "$CI_COMMIT_REF_SLUG"
    paths:
      - input/dvmp
  artifacts:
    paths:
      - input
  script:
    - ./util/run_many.py ./benchmarks/dvmp/gen.sh 
          -c jpsi_barrel 
          -e 10x100 
          --decay muon --decay electron
          --nproc 5

dvmp:process:
  stage: process
  needs: ["detector", "dvmp:generate"]
  timeout: 1 hour
  script:
    - source options/env.sh
    - ./util/compile_analyses.py dvmp
    - ./util/run_many.py ./benchmarks/dvmp/dvmp.sh 
          -c jpsi_barrel 
          -e 10x100 
          --decay muon --decay electron
          --leading jpsi
          --nproc 5
  artifacts:
    paths:
      - results
  retry:
    max: 2
    when:
      - runner_system_failure
  cache:
    key:
      files:
        - .rootlogon.C
        - util/compile_analyses.py
      prefix: "$CI_COMMIT_REF_SLUG"
    paths:
      - .local/root_build

dvmp:results:
  stage: collect
  needs: ["dvmp:process"]
  script:
    - ./util/collect_tests.py dvmp
  artifacts:
    paths:
      - results/dvmp.json
      - results/dvmp
