dvcs:process:
  stage: process
  timeout: 1 hour
  script:
    - bash dvcs/dvcs.sh
  artifacts:
    paths:
      - results

dvcs:results:
  stage: collect
  needs: ["dvcs:process"]
  script:
    - echo "All DVCS benchmarks successful"
