dvcs:process:
  stage: process
  timeout: 1 hour
  needs: ["detector"]
  script:
    - bash dvcs/dvcs.sh
  artifacts:
    paths:
      - results

dvcs:results:
  stage: collect
  needs: ["dvcs:process"]
  script:
    - echo "All DVCS benchmarks successful"
  artifacts:
    paths:
      - results
    reports:
      junit: ["results/dvcs/report.xml"]

