dis:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 dis_compile

dis:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["common:detector", "dis:compile"]
  parallel:
    matrix:
      - EBEAM: 5
        PBEAM: 41
        MINQ2: [1, 10, 100]
      - EBEAM: 10
        PBEAM: 100
        MINQ2: [1, 10, 100, 1000]
      - EBEAM: 18
        PBEAM: 275
        MINQ2: [1, 10, 100, 1000]
  timeout: 2 hours
  script:
    - |
      snakemake --cores 1 \
        results/epic_craterlake/dis/${EBEAM}on${PBEAM}/minQ2=${MINQ2}/dis_${EBEAM}x${PBEAM}_minQ2=${MINQ2}dis_electrons.json \
        results/epic_craterlake/dis/${EBEAM}on${PBEAM}/minQ2=${MINQ2}/jets/ \
        results/epic_craterlake/dis/${EBEAM}on${PBEAM}/minQ2=${MINQ2}/kinematics_correlations/ \
        results/epic_craterlake/dis/${EBEAM}on${PBEAM}/minQ2=${MINQ2}/truth_reconstruction/
  retry:
    max: 2
    when:
      - runner_system_failure

dis:results:
  stage: collect
  needs: ["dis:simulate"]
  script:
    - collect_tests.py dis
