dis:generate:
  stage: generate
  needs: ["common:detector"]
  timeout: 1 hours
  script:
    - bash benchmarks/dis/gen.sh --config barrel --ebeam 18 --pbeam 275

dis:process:
  stage: process
  needs: ["common:detector", "dis:generate"]
  timeout: 1 hour
  script:
    - compile_analyses.py dis
    - ./benchmarks/dis/dis.sh --config barrel --ebeam 18 --pbeam 275
  retry:
    max: 2
    when:
      - runner_system_failure

dis:results:
  stage: collect
  needs: ["dis:process"]
  script:
    - collect_tests.py dis
