dis:generate:
  stage: generate
  extends: .phy_benchmark
  needs: ["common:detector"]
  parallel:
    matrix:
      - EBEAM: 5
        PBEAM: 41
      - EBEAM: 10
        PBEAM: 100
      - EBEAM: 18
        PBEAM: 275
  timeout: 1 hours
  script:
    - bash benchmarks/dis/get.sh --config dis_${EBEAM}x${PBEAM} --ebeam ${EBEAM} --pbeam ${PBEAM}

dis:process:
  stage: process
  extends: .phy_benchmark
  needs: ["common:detector", "dis:generate"]
  parallel:
    matrix:
      - EBEAM: 5
        PBEAM: 41
      - EBEAM: 10
        PBEAM: 100
      - EBEAM: 18
        PBEAM: 275
  timeout: 2 hour
  script:
    - compile_analyses.py dis
    - bash benchmarks/dis/dis.sh --config dis_${EBEAM}x${PBEAM} --ebeam ${EBEAM} --pbeam ${PBEAM}
  retry:
    max: 2
    when:
      - runner_system_failure
  allow_failure: true

dis:results:
  stage: collect
  needs: ["dis:process"]
  script:
    - collect_tests.py dis
