u_channel_rho:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 uchannelrho_compile

u_channel_rho:generate:
  extends: .phy_benchmark
  stage: generate
  needs:
    - ["u_channel_rho:compile"]
  script:
    - echo "Gathering events here!"
    - snakemake --cores 2 benchmark_output/campaign_23.12.0_combined_60files_eicrecon.edm4eic.plots.root
    - echo "Finished, gathering events"

u_channel_rho:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["u_channel_rho:generate"]
  timeout: 96 hour
  script:
    - echo "The simulate task in config.yml does nothing for now"
  retry:
    max: 2
    when:
      - runner_system_failure

u_channel_rho:reconstruct:
  stage: reconstruct
  extends: .phy_benchmark
  needs: ["u_channel_rho:simulate"]
  timeout: 96 hour
  script:
    - echo "The reconstruct task in config.yml does nothing for now"
  retry:
    max: 2
    when:
      - runner_system_failure

u_channel_rho:analyze:
  extends: .phy_benchmark
  stage: analyze
  needs:
    - ["u_channel_rho:reconstruct"]
  script:
    - echo "I will be analyzing events here!"
    - snakemake --cores 2 benchmark_output/campaign_23.12.0_combined_60files_eicrecon.edm4eic.plots_figures/benchmark_rho_mass.pdf
    - echo "Finished, copying over figures now"
    - mkdir results
    - mkdir results/u_rho
    - cp benchmark_output/campaign_23.12.0_combined_60files_eicrecon.edm4eic.plots_figures/*.pdf results/u_rho/
    - cp benchmark_output/u_rho_eff.json results/u_rho/
    - echo "Finished copying!" 

u_channel_rho:results:
  stage: collect
  needs: ["u_channel_rho:analyze"]
  script:
     - collect_tests.py u_rho
     - echo "Finished collecting!"
