u_channel_rho:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 uchannelrho_compile

#u_channel_rho:sim:
#  extends: .phy_benchmark 
#  stage: simulate
#  script:
#    - echo "I will be simulating u-channel rho events here!"
#    - echo $LOCAL_DATA_PATH/u_channel_rho

u_channel_rho:generate:
  extends: .phy_benchmark
  stage: generate
  needs:
    - ["u_channel_rho:compile"]
  script:
    - echo "I will be analyzing events here!"
    - snakemake --cores 2 benchmark_output/campaign_23.12.0_combined_60files_eicrecon.edm4eic.plots_figures/benchmark_rho_mass.pdf
    - echo "Finished" 

u_channel_rho:results:
  stage: collect
  needs: ["u_channel_rho:simulate"]
  script:
    - cp benchmark_output/campaign_23.12.0_combined_60files_eicrecon.edm4eic.plots_figures/*.pdf figures/
