dvcs:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 dvcs_compile

dvcs:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["dvcs:compile"]
  timeout: 2 hours
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 dvcs_run_locally
  retry:
    max: 2
    when:
      - runner_system_failure

dvcs:results:
  stage: collect
  needs: ["dvcs:simulate"]
  script:
    - collect_tests.py Exclusive-Diffraction-Tagging/dvcs
