diffractive_vm:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 diffractive_vm_compile

diffractive_vm:simulate:
  stage: simulate
  extends: .phy_benchmark
  parallel:
    matrix:
      - VM: phi
      - VM: jpsi
  timeout: 2 hours
  script:
    - snakemake --cache --cores 10 diffractive_vm_run_locally
  retry:
    max: 2
    when:
      - runner_system_failure

diffractive_vm:results:
  stage: collect
  needs: ["diffractive_vm:simulate"]
  script:
    - collect_tests.py Exclusive-Diffraction-Tagging/diffractive_vm
