dvmp:generate:
  image: eicweb.phy.anl.gov:4567/monte_carlo/lager/lager:unstable
  stage: generate
  needs: []
  timeout: 1 hours
  cache:
    key:
      files:
        - dvmp/generator/jpsi_central.json
        - dvmp/scripts/jpsi_central-generate.sh
      prefix: "$CI_COMMIT_REF_SLUG"
    paths:
      - results/dvmp
  artifacts:
    paths:
      - results
  script:
    - ./dvmp/scripts/generate.sh --ebeam 10 --pbeam 100 --config jpsi_central --decay muon --decay electron

dvmp:jpsi_central:process:
  stage: process
  needs: ["dvmp:generate"]
  timeout: 1 hour
  script:
    - bash dvmp/dvmp.sh
  artifacts:
    paths:
      - results

dvmp:jpsi_central:test_analysis:
  stage: analyze
  needs: ["dvmp:jpsi_central:process"]
  script:
    - echo "THIS IS A PLACE HOLDER"


dvmp:results:
  stage: collect
  needs: ["dvmp:jpsi_central:test_analysis"]
  script:
    - echo "All DVMP benchmarks successful"
