dvmp:generate:
  image: eicweb.phy.anl.gov:4567/monte_carlo/lager/lager:unstable
  stage: initialize
  needs: []
  timeout: 1 hours
  cache:
    key:
      files:
        - dvmp/generator/jpsi_central.json
        - dvmp/scripts/jpsi_central-generate.sh
      prefix: "$CI_COMMIT_REF_SLUG"
    paths:
      - input/dvmp
  artifacts:
    paths:
      - input
  script:
    - ./util/run_many.py ./dvmp/gen.sh --energy 10x100 --config jpsi_central --decay muon --decay electron

dvmp:process:
  stage: process
  needs: ["detector", "dvmp:generate"]
  timeout: 1 hour
  script:
    - ./util/run_many.py dvmp/dvmp.sh --energy 10x100 --config jpsi_central --decay muon --decay electron --leading jpsi
  artifacts:
    paths:
      - results

dvmp:results:
  stage: collect
  needs: ["dvmp:process"]
  script:
    - echo "All DVMP benchmarks successful"
