test_srmyoo:compile:
  extends: .phy_benchmark 
  stage: compile
  script:
    - echo "You can compile your code here!"

test_srmyoo:simulate:
  extends: .phy_benchmark
  stage: simulate
  script:
    - echo "I will simulate detector response here!"

test_srmyoo:results:
  extends: .phy_benchmark
  stage: collect
  script:
    - echo "I will collect results here!"

