
lambda:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["common:detector"]
  parallel:
    matrix:
      - P: 100
      - P: 125
      - P: 150
      - P: 175
      - P: 200
      - P: 225
      - P: 250
      - P: 275
  timeout: 6 hours
  script:
    - snakemake --cores 1 results/lambda/epic_zdc_sipm_on_tile_only_rec_lambda_dec_${P}GeV.edm4hep.root 
  retry:
    max: 2
    when:
      - runner_system_failure

lambda:results:
  stage: collect
  needs: ["lambda:simulate"]
  script:
    - python benchmarks/lambda/analysis/lambda_plots.py results/lambda/results_epic_zdc_sipm_on_tile_only_lambda_dec
