neutron:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["common:detector"]
  parallel:
    matrix:
      - P: 20
      - P: 30
      - P: 40
      - P: 50
      - P: 60
      - P: 70
      - P: 80
  timeout: 1 hours
  script:
    - snakemake --cores 1 sim_output/neutron/epic_zdc_sipm_on_tile_only_rec_neutron_${P}GeV.edm4hep.root 
  retry:
    max: 2
    when:
      - runner_system_failure

neutron:analyze:
  stage: analyze
  extends: .phy_benchmark
  needs: ["neutron:simulate"]
  script:
    - snakemake --cores 1 results/epic_zdc_sipm_on_tile_only/neutron 

neutron:results:
  stage: collect
  needs: ["neutron:analyze"]
  script:
    - ls -al
