diffractive_vm:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - snakemake --cores 1 diffractive_vm_compile

diffractive_vm:generate:
  stage: generate
  extends: .phy_benchmark
  needs: ["common:detector", "diffractive_vm:compile"]
  parallel:
    matrix:
      - VM: phi
      - VM: jpsi
  timeout: 1 hours
  script:
    - snakemake --cores 1 sartre_${VM}_{000,001,002,003,004,005,006,007,008,009}.hepmc.gz

diffractive_vm:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["diffractive_vm:generate"]
  parallel:
    matrix:
      - VM: phi
      - VM: jpsi
  timeout: 96 hour
  script:
    - snakemake --cores 1 sartre_${VM}_combined_9/plots_benchmark-phi-dsigmadt.pdf
  retry:
    max: 2
    when:
      - runner_system_failure

diffractive_vm:results:
  stage: collect
  needs: ["diffractive_vm:simulate"]
  script:
    - collect_tests.py diffractive_vm
