diffractive_vm:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py diffractive_vm

diffractive_vm:generate:
  stage: generate
  extends: .phy_benchmark
  needs: ["common:detector", "diffractive_vm:compile"]
  parallel:
    matrix:
      - VM: phi
      - VM: jpsi
  timeout: 1 hours
  script:
    # FIXME eAu beams
    - bash benchmarks/diffractive_vm/get.sh --config diffractive_${VM} --leading ${VM} --ebeam 18 --pbeam 110

diffractive_vm:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["diffractive_vm:generate"]
  parallel:
    matrix:
      - VM: phi
      - VM: jpsi
  timeout: 96 hour
  script:
    # FIXME eAu beams
    - bash benchmarks/diffractive_vm/diffractive_vm.sh --config diffractive_${VM} --leading ${VM} --ebeam 18 --pbeam 110
  retry:
    max: 2
    when:
      - runner_system_failure

diffractive_vm:results:
  stage: collect
  needs: ["diffractive_vm:simulate"]
  script:
    - collect_tests.py diffractive_vm
