u_omega:compile:
  stage: compile
  extends: .compile_benchmark
  script:
    - compile_analyses.py Exclusive-Diffraction-Tagging/u_omega

u_omega:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["u_omega:compile"]
  script:
    #- bash benchmarks/Exclusive-Diffraction-Tagging/u_omega/u_omega.sh --all
    - bash benchmarks/Exclusive-Diffraction-Tagging/u_omega/u_omega.sh --data-init --sim --rec

u_omega:results:
  stage: collect
  needs: ["u_omega:simulate"]
  script:
    - ls -lrth
