dvcs:process:
  stage: process
  timeout: 1 hour
  needs: ["detector"]
  script:
    - bash benchmarks/dvcs/dvcs.sh
  artifacts:
    paths:
      - results

dvcs:results:
  stage: collect
  needs: ["dvcs:process"]
  script:
    - pip install junitparser
      #- python dvcs/scripts/merge_results.py
  artifacts:
    paths:
      - results
        #  reports:
