dvcs:process:
  stage: process
  extends: .phy_benchmark
  tags:
    - s3
  needs: ["common:detector"]
  script:
    - compile_analyses.py dvcs
    - bash benchmarks/dvcs/dvcs.sh --all

dvcs:results:
  stage: collect
  needs: ["dvcs:process"]
  script:
    - ls -lrth
      #pip install junitparser
      #- python dvcs/scripts/merge_results.py
