# diffractive_phi:process:
#   stage: process
#   extends: .phy_benchmark
#   tags:
#     - s3
#   needs: ["common:detector"]
#   script:
#     - bash benchmarks/diffractive_phi/diffractive_phi.sh --all

# diffractive_phi:results:
#   stage: collect
#   needs: ["diffractive_phi:process"]
#   script:
#     - ls -lrth
