diffractive_phi:process:
  stage: process
  extends: .phy_benchmark
  tags:
     - phy
  needs: ["common:detector"]
  script:
    - compile_analyses.py diffractive_phi
    - bash benchmarks/diffractive_phi/diffractive_phi.sh --all

diffractive_phi:results:
  stage: collect
  needs: ["diffractive_phi:process"]
  script:
    - ls -lrth

